---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeautomationdeployment
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:2021.3.4
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
        - name: config
          hostPath:
            path: /home/packet
