---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/raspberrypi4-homeassistant:2021.3.4
        ports:
        - containerPort: 8123
          name: http
#        volumeMounts:
#        - mountPath: /config
#          name: config
#      volumes:
#        - name: config
#          hostPath:
#            path: config
