
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

tplink:
  discovery: false
  switch:
    - host: 192.168.1.134
    - host: 192.168.1.155

sensor:
  - platform: template
    sensors:
      my_tp_switch_amps:
        friendly_name_template: "{{ state_attr('switch.enchufe','friendly_name') }} Current"
        value_template: "{{ state_attr('switch.enchufe','current_a') }}"
        unit_of_measurement: "A"
      my_tp_switch_watts:
        friendly_name_template: "{{ state_attr('switch.enchufe','friendly_name') }} Current Consumption"
        value_template: "{{ state_attr('switch.enchufe','current_power_w') }}"
        unit_of_measurement: "W"
      my_tp_switch_total_kwh:
        friendly_name_template: "{{ state_attr('switch.enchufe','friendly_name') }} Total Consumption"
        value_template: "{{ state_attr('switch.enchufe','total_energy_kwh') }}"
        unit_of_measurement: "kWh"
      my_tp_switch_volts:
        friendly_name_template: "{{ state_attr('switch.enchufe','friendly_name') }} Voltage"
        value_template: "{{ state_attr('switch.enchufe','voltage') }}"
        unit_of_measurement: "V"
      my_tp_switch_today_kwh:
        friendly_name_template: "{{ state_attr('switch.enchufe','friendly_name') }} Today's Consumption"
        value_template: "{{ state_attr('switch.enchufe','today_energy_kwh') }}"
        unit_of_measurement: "kWh"

localtuya:
  - host: 192.168.1.153
    device_id: 50134218c4dd571b0a23
    local_key: 1ef49e1a7515d00d
    friendly_name: smart power strip
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: switch_1
        id: 1
      - platform: switch
        friendly_name: switch_2
        id: 2
      - platform: switch
        friendly_name: switch_3
        id: 3
      - platform: switch
        friendly_name: switch_4
        id: 4
      - platform: switch
        friendly_name: switch_usb
        id: 7
      - platform: switch
        friendly_name: switch_all
        id: 38
